[ISSUE-125] Make sure the callback handler is always called in caller context
vert-x3/vertx-mail-client pull request #157
Opened 2020-10-09 08:41 UTC by gaol

Motivation:

Fixes #125 

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

Looks like that current implementation already makes sure that [the call back handler is always called in the caller context](https://github.com/vert-x3/vertx-mail-client/blob/15d9c72c91fdffcb0426fa5cecc63c1014966359/src/main/java/io/vertx/ext/mail/impl/MailClientImpl.java#L202), but without test to guarantee that, this PR added a test only to make sure it won't break the context model in the future development.

2020-10-09 08:44 UTC, gaol commented
@vietj Would you please review to check if I understand the context model correctly by checking the test in this PR? Thanks :)

2020-10-11 08:44 UTC, vietj commented
so from this PR this is already correct but we are simply adding tests to ensure it is.

2020-10-11 08:45 UTC, vietj commented
alright that's what the description says :-)

2020-10-11 08:47 UTC, vietj commented
can we do a test without event bus ? because event-bus consumer will create a context duplicate (which has the same event loop). I think we should test that a simple verticle sending an email will get as callback the exact same context instance.

2020-10-11 08:48 UTC, vietj requested changes
one verticle should not use event-bus consumer

2020-10-12 04:39 UTC, gaol commented
@vietj Thanks for the review. updated as suggested. :)

2020-10-19 07:26 UTC, merged

2020-10-19 07:26 UTC, vietj commented
thanks for the contribution @gaol