Header encoding fix
vert-x3/vertx-mail-client pull request #216
Opened 2023-07-04 02:27 UTC by ffcactus

Motivation:

Line folding should consider the Unicode that occupies more than one byte.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md.
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2023-07-04 02:33 UTC, ffcactus commented on src/test/java/io/vertx/ext/mail/mailencoder/MailEncoderTest.java
> +      + " user3@example.com (=?UTF-8?Q?=C3=84a?=),user4@example.com (=?UTF-8?Q??=\n"
As you can see, `=C3=84` should not fold into the next line.
But also note that we may have "**??=**\n" at the end of the line, but I think is allowed.

2023-07-04 06:01 UTC, gaol requested changes
Thanks @ffcactus for the contribution, I have several comments, please take a look.

2023-07-04 06:08 UTC, gaol commented
Please make sure you are using correct email (good format and the one you are using to sign ECA) in the git commit, I see your email in the git commits is: `bin.bai@bin.bai@rakuten.com`, which looks not a valid email address..

And it would be better to squash your commits into 1. thanks :)

2023-07-04 15:23 UTC, ffcactus commented
> Please make sure you are using correct email (good format and the one you are using to sign ECA) in the git commit, I see your email in the git commits is: `bin.bai@bin.bai@rakuten.com`, which looks not a valid email address..
> 
> And it would be better to squash your commits into 1. thanks :)

Should I squash the commits into a single one and force push or make a squashed PR that squashes the commits after the review?

2023-07-05 02:35 UTC, gaol commented
@ffcactus you can squash and force push to update this PR.

2023-07-05 07:03 UTC, ffcactus commented
Sorry, I think I messed up this PR. 
I'm going to discord this PR. Please refer to https://github.com/vert-x3/vertx-mail-client/pull/217

2023-07-05 07:03 UTC, closed without merging